version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: wgtadmin
      POSTGRES_DB: wgt
  app:
    image: wgt
    ports:
      - 13000:3000